/// <reference types="nativewind/types" />
<<<<<<< HEAD

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.
=======
>>>>>>> 33a7c515026043d68b7ea7b0c84daab7a315cac5
